CREATE TABLE IF NOT EXISTS `coupons` (
  `id` int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `coupon_type` varchar(255) NOT NULL,
  `begin_date` TIMESTAMP NOT NULL,
  `expired_date` TIMESTAMP NOT NULL,
  `category` varchar(255) NOT NULL,
  `discount` int NOT NULL,
  `max_discount_amount` int NOT NULL,
  `min_transaction_amount` int NOT NULL,
  `payment_method` varchar(255) NOT NULL,
  `member_type` varchar(255) NOT NULL,
  `image_url` varchar(255) NOT NULL,
  `description` varchar(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP,
);
