// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewCoupon struct {
	Title                string `json:"title"`
	CouponType           string `json:"couponType"`
	Category             string `json:"category"`
	Discount             int64  `json:"discount"`
	MaxDiscountAmount    int64  `json:"maxDiscountAmount"`
	MinTransactionAmount int64  `json:"minTransactionAmount"`
	PaymentMethod        string `json:"paymentMethod"`
	MemberType           string `json:"memberType"`
	ImageURL             string `json:"imageUrl"`
	Description          string `json:"description"`
}

type NewUser struct {
	Name       string       `json:"name"`
	MemberType string       `json:"memberType"`
	Coupons    []*NewCoupon `json:"coupons"`
}
